### PR TITLE
Fixes Rails 6.1 deprecations

### LINKED ISSUE #422: Deprecation warning in Rails 6.1
Hi,

i'm using ruby 2.6.5 and rails 6.1
I get this warning when calling `descendants` method.

```
DEPRECATION WARNING: Class level methods will no longer inherit scoping from `###` in Rails 6.1. To continue using the scoped relation, pass it into the block directly. To instead access the full set of models, as Rails 6.1 will, use `Model.unscoped`, or `Model.default_scoped` if a model has default scopes.
```

any idea ?

### PR DESCRIPTION
**Pull request by marcrohloff**
Fixes #422 Rails 6.1 deprecations of the form:

> DEPRECATION WARNING: Class level methods will no longer inherit scoping from `###` in Rails 6.1. To continue using the scoped relation, pass it into the block directly. To instead access the full set of models, as Rails 6.1 will, use `Model.unscoped`, or `Model.default_scoped` if a model has default scopes.

### CODE REVIEW

File: lib/awesome_nested_set/model.rb [hunk 1]
```diff
@@ -95,6 +99,12 @@ def root
           def roots
             nested_set_scope.children_of nil
           end
+
+          private
+
+          def scope_order_from_options(options)
+            options[:order] || { order_column_name => :asc }
```
Comment (parndt) [inline lib/awesome_nested_set/model.rb:106]: Maybe we should use fetch:

```suggestion
            options.fetch(:order) { { order_column_name => :asc } }
```

Comment (marcrohloff) [reply lib/awesome_nested_set/model.rb:106]: I assume you mean ?
```
options.fetch(:order, { { order_column_name => :asc }) 
```

It seems about the same thing

Comment (parndt) [reply lib/awesome_nested_set/model.rb:106]: Yeah, fetch takes a second argument, or a block so it can be 
```ruby
options.fetch(:order) { { order_column_name => :asc } }
```

or it can be
```ruby
options.fetch(:order, { order_column_name => :asc })
```

Whatever is your preference 👍

**Comment by parndt** [comment]
This change looks good @marcrohloff but for some reason fails in Ruby 2.5.x https://travis-ci.org/github/collectiveidea/awesome_nested_set/jobs/721862703#L321

**Review by parndt — APPROVED** [review]

**Comment by aualdrich** [comment]
Thanks for the fix!

File: lib/awesome_nested_set/model.rb [hunk 2]
```diff
@@ -79,9 +79,13 @@ def right_of(node)
...
-            options = {:order => { order_column_name => :asc }}.merge(options)
+            order = scope_order_from_options(options)
+            default_scoped.where(options[:conditions]).order(order)
+          end
 
-            where(options[:conditions]).order(options.delete(:order))
+          def nested_set_scope_without_default_scope(options = {})
+            order = scope_order_from_options(options)
+            unscoped.where(options[:conditions]).order(order)
           end
```
Comment (kvognar) [inline lib/awesome_nested_set/model.rb:90]: I know this is an old release by now, but I believe this change breaks the behavior of `root` and `roots` when there's already an established scope on the ActiveRecord relation. `roots` does not pass any of the scope options along to `nested_set_scope`, so that information is lost when you use `default_scoped` and `unscoped` instead of `where`.

For example, if I have an association between `User` and `Comment` where comments are a nested set, `user.comments.roots` would previously return all root comments that belong to the user. Now it returns *all root comments by any user*. This isn't intended behavior, is it?

@marcrohloff @aualdrich sorry if I'm not going through the right channels, but I ran into this issue while upgrading this gem. If it's more appropriate to make an Issue I can do that, but perhaps this change is 100% intentional and I'm just misusing Awesome Nested Set, so I wanted to better understand why this change was made.

Comment (kvognar) [reply lib/awesome_nested_set/model.rb:90]: Sorry, it looks like this was addressed in https://github.com/collectiveidea/awesome_nested_set/pull/437 . I first ran into this issue a couple months ago, and it seems that since then the issue has been resolved. 😅
